config/routes.rb
Rails.application.routes.draw do
  get "/projects", to: "projects#index"
  get "/projects/new", to: "projects#new"
  get "projects/:id", to: "projects#show", as: "project"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :read_project
    def index
    end 

    def show 
        @project = @projects.find do |project|
            project[:id] == params[:id].to_i 
        end 
    end 

    def new
    end 

    private 
    def read_project 
        @projects = [
            {
                id: 1,
                name: "terminal app",
                github_status: true,
                date_completed: "17/08/2020"
            },
            {
                id: 2,
                name: "react app",
                github_status: false,
                date_completed: "20/10/2020"
            }
        ]
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagementAppViews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/projects/_card.html.erb
<li class="card"> <%= link_to project[:name], project_path(project[:id]) %> 
    <ul>
        <li>Github status: <%= project[:github_status] == true ? "✅" : "❌" %></li>
		<li>Date completed: <%= project[:date_completed] %></li>
	</ul>
</li>

app/views/projects/index.html.erb
<h1>Projects</h1>
<h2>Projects List 🔖</h2>
<%= image_tag asset_path("puppy.jpeg"), width: 400 %>
<ul>
    <% @projects.each do |project| %>
        <%= render partial: "card", locals: { project: project } %>
    <% end %>
</ul>

app/views/projects/show.html.erb
<h1>Project</h1>

<ul>
    <li> <%= link_to @project[:name], project_path(@project[:id]) %> </li>
	<ul>
		<li>Github status: <%= @project[:github_status] == true ? "✅" : "❌" %></li>
		<li>Date completed: <%= @project[:date_completed] %></li>
	</ul>
</ul>

app/views/shared/_nav.html.erb
<nav>
    <%= link_to "Projects", projects_path %>
    <%= link_to "New project page", projects_new_path %>
</nav>